# Generated by Django 2.0.8 on 2018-10-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='letter_1_send_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='check',
            name='letter_2_send_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='check',
            name='letter_3_send_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
