# Generated by Django 2.1.2 on 2018-11-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='letter_1_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='check',
            name='letter_2_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='check',
            name='letter_3_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
