# Generated by Django 2.0.8 on 2018-10-11 16:22

import checks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0002_auto_20181011_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[checks.models.validate_positive]),
        ),
    ]
