# Generated by Django 2.1.2 on 2018-10-28 01:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name1', models.CharField(max_length=200)),
                ('last_name1', models.CharField(default='', max_length=200)),
                ('first_name2', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name2', models.CharField(blank=True, max_length=200, null=True)),
                ('street_addr', models.CharField(default='', max_length=200)),
                ('city_addr', models.CharField(default='', max_length=200)),
                ('state_addr', models.CharField(default='', max_length=200)),
                ('zip_addr', models.CharField(default='', max_length=200)),
                ('account_num', models.CharField(max_length=50)),
                ('phone_num', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routing_n', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(default='bank', max_length=500)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_num', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('wait_period', models.DurationField(blank=True, default=datetime.timedelta(10))),
                ('late_fee', models.DecimalField(blank=True, decimal_places=2, default=25, max_digits=15)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_num', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='routing_num',
            field=models.ForeignKey(null=True, on_delete=models.SET(None), to='accounts.Bank'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('routing_num', 'account_num')},
        ),
    ]
