# Generated by Django 2.0.8 on 2018-09-12 00:02

import accounts.models
import address.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0002_auto_20160213_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('routing_num', models.CharField(max_length=50)),
                ('account_num', models.CharField(max_length=50)),
                ('addr', address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[accounts.models.validate_positive])),
                ('made_date', models.DateField()),
                ('check_num', models.PositiveIntegerField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('from_account', models.ForeignKey(help_text='routing#:account#', on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='check',
            name='to_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Client'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('routing_num', 'account_num')},
        ),
    ]
