# Generated by Django 2.1.2 on 2018-11-28 05:08

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181106_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='letter_1_template',
            field=models.CharField(blank=True, default='\n{date}\n\nDear {recipient_name}:\n\nCheck {check_num} you wrote for ${check_amt}, dated {made_date}, which was made payable to {to_client} was returned by your bank, {bank_name}.\nUnless full payment of the check is received by cash within {wait_period} days after the date this demand letter was mailed, together with ${late_fee} in bank fees, we will file a small claims court claim against you.\nYou may wish to contact a lawyer to discuss your legal rights and responsibilities.\nSincerely,\nCheck Hunters\n', max_length=5000, validators=[accounts.models.validate_template]),
        ),
        migrations.AlterField(
            model_name='client',
            name='letter_2_template',
            field=models.CharField(blank=True, default='\n{date}\n\nDear {recipient_name}:\n\nCheck {check_num} you wrote for ${check_amt}, dated {made_date}, which was made payable to {to_client} was returned by your bank, {bank_name}.\nUnless full payment of the check is received by cash within {wait_period} days after the date this demand letter was mailed, together with ${late_fee} in bank fees, we will file a small claims court claim against you.\nYou may wish to contact a lawyer to discuss your legal rights and responsibilities.\nSincerely,\nCheck Hunters\n', max_length=5000, validators=[accounts.models.validate_template]),
        ),
        migrations.AlterField(
            model_name='client',
            name='letter_3_template',
            field=models.CharField(blank=True, default='\n{date}\n\nDear {recipient_name}:\n\nCheck {check_num} you wrote for ${check_amt}, dated {made_date}, which was made payable to {to_client} was returned by your bank, {bank_name}.\nUnless full payment of the check is received by cash within {wait_period} days after the date this demand letter was mailed, together with ${late_fee} in bank fees, we will file a small claims court claim against you.\nYou may wish to contact a lawyer to discuss your legal rights and responsibilities.\nSincerely,\nCheck Hunters\n', max_length=5000, validators=[accounts.models.validate_template]),
        ),
    ]
