# Generated by Django 2.0.8 on 2018-09-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180922_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('routing_num', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='routing_num',
            field=models.ForeignKey(null=True, on_delete=models.SET(None), to='accounts.Bank'),
        ),
    ]
