# Generated by Django 2.1.2 on 2018-11-30 04:22

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181128_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='routing_num',
            field=accounts.models.StringToFK(null=True, on_delete=models.SET(None), to='accounts.Bank'),
        ),
    ]
