# Generated by Django 2.1.2 on 2018-11-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181129_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='routing_num',
            field=models.ForeignKey(null=True, on_delete=models.SET(None), to='accounts.Bank'),
        ),
    ]
