# Generated by Django 2.0.8 on 2018-10-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181011_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='first_name2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
