# Generated by Django 2.0.8 on 2018-10-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20181011_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='contact_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='phone_num',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
