# Generated by Django 2.0.8 on 2018-10-11 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20181011_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='late_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=25, max_digits=15),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_num',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='wait_period',
            field=models.DurationField(blank=True, default=datetime.timedelta(10)),
        ),
    ]
