# Generated by Django 2.0.8 on 2018-10-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20181011_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='addr',
        ),
        migrations.AddField(
            model_name='account',
            name='city_addr',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='account',
            name='state_addr',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='account',
            name='street_addr',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='account',
            name='zip_addr',
            field=models.CharField(default='', max_length=200),
        ),
    ]
