# Generated by Django 2.0.8 on 2018-09-25 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180925_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='routing_num',
            new_name='routing_n',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='name',
        ),
    ]
