# Generated by Django 2.0.8 on 2018-09-25 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_date', models.DateField()),
                ('letter_template', models.CharField(choices=[('letter1', '1st'), ('letter2', '2nd'), ('letter3', '3rd')], max_length=100)),
                ('check_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checks.Check')),
            ],
        ),
    ]
